// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoteWaves.Data;

#nullable disable

namespace NotesWave.Data.Migrations
{
    [DbContext(typeof(NotesWaveDBContext))]
    [Migration("20250213074756_RemoveDescRelTable")]
    partial class RemoveDescRelTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NotesWave.Data.Models.Description.Description", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoteId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("NoteId");

                    b.ToTable("Descriptions");
                });

            modelBuilder.Entity("NotesWave.Data.Models.Note.Note", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("NotesWave.Data.Models.Note.NoteRels", b =>
                {
                    b.Property<string>("NoteID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NoteRelID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("NoteID", "NoteRelID");

                    b.HasIndex("NoteRelID");

                    b.ToTable("NoteRels");
                });

            modelBuilder.Entity("NotesWave.Data.Models.Note.NoteSketch", b =>
                {
                    b.Property<string>("NoteID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SketchID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("NoteID", "SketchID");

                    b.HasIndex("SketchID");

                    b.ToTable("NoteSketches");
                });

            modelBuilder.Entity("NotesWave.Data.Models.Sketch.Sketch", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Coordinates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Sketches");
                });

            modelBuilder.Entity("NotesWave.Data.Models.Description.Description", b =>
                {
                    b.HasOne("NotesWave.Data.Models.Note.Note", null)
                        .WithMany("Descriptions")
                        .HasForeignKey("NoteId");
                });

            modelBuilder.Entity("NotesWave.Data.Models.Note.NoteRels", b =>
                {
                    b.HasOne("NotesWave.Data.Models.Note.Note", "Note")
                        .WithMany("RelatedNotes")
                        .HasForeignKey("NoteID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NotesWave.Data.Models.Note.Note", "NoteRel")
                        .WithMany()
                        .HasForeignKey("NoteRelID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Note");

                    b.Navigation("NoteRel");
                });

            modelBuilder.Entity("NotesWave.Data.Models.Note.NoteSketch", b =>
                {
                    b.HasOne("NotesWave.Data.Models.Note.Note", "Note")
                        .WithMany("NoteSketches")
                        .HasForeignKey("NoteID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NotesWave.Data.Models.Sketch.Sketch", "Sketch")
                        .WithMany()
                        .HasForeignKey("SketchID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Note");

                    b.Navigation("Sketch");
                });

            modelBuilder.Entity("NotesWave.Data.Models.Note.Note", b =>
                {
                    b.Navigation("Descriptions");

                    b.Navigation("NoteSketches");

                    b.Navigation("RelatedNotes");
                });
#pragma warning restore 612, 618
        }
    }
}
